In [25]:
import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

import tensorflow as tf
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

In [26]:
df = pd.read_csv("Student_Data.csv")

print(df.shape)
df.head()

(2000, 18)

,id,sgpa1,sgpa2,sgpa3,sgpa4,cgpa,active_backlogs,total_backlogs,10th_mark,12th_mark,studytime,part_timejob,math,dsa,networks,os,attendance,career_preference
0,1,6.79,7.94,7.12,6.22,7.02,0,0,81.91,84.23,13,no,52,88,90,85,85.93,higher study
1,2,9.82,5.18,7.00,6.27,7.07,0,0,45.37,33.45,10,yes,37,34,81,81,71.06,job
2,3,6.74,6.52,6.53,7.96,6.94,0,0,56.23,64.97,0,yes,50,48,50,86,70.80,higher study
3,4,8.72,8.62,4.71,7.46,7.38,0,0,77.44,86.19,2,yes,97,58,77,88,97.16,job
4,5,6.75,7.84,7.82,8.37,7.70,4,5,65.31,75.22,2,yes,55,53,37,71,72.13,none

In [27]:
# Drop id if present
if "id" in df.columns:
    df = df.drop(columns=["id"])

# Encode part_timejob
if df["part_timejob"].dtype == "object":
    df["part_timejob"] = df["part_timejob"].map({"yes":1,"no":0})

# Encode career_preference
le = LabelEncoder()
df["career_preference"] = le.fit_transform(df["career_preference"])

In [28]:
df["avg_sgpa_4"] = (df["sgpa1"] + df["sgpa2"] + df["sgpa3"] + df["sgpa4"]) / 4

df["sgpa_trend"] = df["sgpa4"] - df["sgpa1"]

df["recent_trend"] = df["sgpa4"] - df["sgpa3"]

df["academic_score"] = (
    df["math"] + df["dsa"] + df["networks"] + df["os"]
) / 4

In [29]:
df["sgpa5"] = (
    df["avg_sgpa_4"]
    + 0.4 * df["recent_trend"]
    + 0.2 * df["sgpa_trend"]
    + 0.01 * (df["attendance"] - 75)
    + 0.005 * (df["academic_score"] - 70)
)

df["sgpa5"] = df["sgpa5"].clip(0,10)

In [30]:
X = df.drop(columns=["sgpa5"])
y = df["sgpa5"]

print("Features:", X.shape)

Features: (2000, 21)

In [31]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [32]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Save scaler
joblib.dump(scaler, "scaler.pkl")

print("Scaler saved")

Scaler saved

In [33]:
model = Sequential()

model.add(Dense(64, activation="relu", input_shape=(X_train.shape[1],)))
model.add(Dense(32, activation="relu"))
model.add(Dense(16, activation="relu"))
model.add(Dense(1))

model.compile(
    optimizer="adam",
    loss="mse",
    metrics=["mae"]
)

model.summary()

c:\Users\Asus\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 64)             │         1,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,033 (15.75 KB)

 Trainable params: 4,033 (15.75 KB)

 Non-trainable params: 0 (0.00 B)

In [34]:
early_stop = EarlyStopping(
    monitor="val_loss",
    patience=10,
    restore_best_weights=True
)

history = model.fit(
    X_train,
    y_train,
    validation_split=0.2,
    epochs=150,
    batch_size=16,
    callbacks=[early_stop]
)

Epoch 1/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 24.3194 - mae: 4.2374 - val_loss: 2.8485 - val_mae: 1.2658
Epoch 2/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.6634 - mae: 1.0196 - val_loss: 1.2702 - val_mae: 0.8875
Epoch 3/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.1286 - mae: 0.8553 - val_loss: 1.0150 - val_mae: 0.8046
Epoch 4/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.8878 - mae: 0.7549 - val_loss: 0.8388 - val_mae: 0.7322
Epoch 5/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.7157 - mae: 0.6774 - val_loss: 0.7257 - val_mae: 0.6843
Epoch 6/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6002 - mae: 0.6201 - val_loss: 0.6208 - val_mae: 0.6325
Epoch 7/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5013 - mae: 0.5619 - val_loss: 0.5552 - val_mae: 0.5896
Epoch 8/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4262 - mae: 0.5163 - val_loss: 0.4880 - val_mae: 0.5571
Epoch 9/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3709 - mae: 0.4811 - val_loss: 0.4285 - val_mae: 0.5208
Epoch 10/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3196 - mae: 0.4463 - val_loss: 0.3811 - val_mae: 0.4927
Epoch 11/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2780 - mae: 0.4124 - val_loss: 0.3325 - val_mae: 0.4545
Epoch 12/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2386 - mae: 0.3829 - val_loss: 0.3051 - val_mae: 0.4360
Epoch 13/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2094 - mae: 0.3582 - val_loss: 0.2832 - val_mae: 0.4302
Epoch 14/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1845 - mae: 0.3349 - val_loss: 0.2464 - val_mae: 0.3972
Epoch 15/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1615 - mae: 0.3124 - val_loss: 0.2373 - val_mae: 0.3943
Epoch 16/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1398 - mae: 0.2941 - val_loss: 0.1984 - val_mae: 0.3618
Epoch 17/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1243 - mae: 0.2731 - val_loss: 0.1852 - val_mae: 0.3414
Epoch 18/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1081 - mae: 0.2582 - val_loss: 0.1795 - val_mae: 0.3419
Epoch 19/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0978 - mae: 0.2461 - val_loss: 0.1578 - val_mae: 0.3162
Epoch 20/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0835 - mae: 0.2267 - val_loss: 0.1453 - val_mae: 0.3050
Epoch 21/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0741 - mae: 0.2135 - val_loss: 0.1442 - val_mae: 0.2998
Epoch 22/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0647 - mae: 0.2006 - val_loss: 0.1298 - val_mae: 0.2843
Epoch 23/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0587 - mae: 0.1908 - val_loss: 0.1236 - val_mae: 0.2784
Epoch 24/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0533 - mae: 0.1814 - val_loss: 0.1213 - val_mae: 0.2781
Epoch 25/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0468 - mae: 0.1680 - val_loss: 0.1049 - val_mae: 0.2559
Epoch 26/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0430 - mae: 0.1624 - val_loss: 0.0971 - val_mae: 0.2463
Epoch 27/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0371 - mae: 0.1518 - val_loss: 0.0966 - val_mae: 0.2452
Epoch 28/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0331 - mae: 0.1439 - val_loss: 0.0900 - val_mae: 0.2381
Epoch 29/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0306 - mae: 0.1382 - val_loss: 0.0890 - val_mae: 0.2294
Epoch 30/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0283 - mae: 0.1344 - val_loss: 0.0772 - val_mae: 0.2181
Epoch 31/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0262 - mae: 0.1275 - val_loss: 0.0792 - val_mae: 0.2183
Epoch 32/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0244 - mae: 0.1238 - val_loss: 0.0785 - val_mae: 0.2200
Epoch 33/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0229 - mae: 0.1217 - val_loss: 0.0666 - val_mae: 0.2019
Epoch 34/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0213 - mae: 0.1159 - val_loss: 0.0641 - val_mae: 0.1986
Epoch 35/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0176 - mae: 0.1055 - val_loss: 0.0590 - val_mae: 0.1887
Epoch 36/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0162 - mae: 0.1012 - val_loss: 0.0570 - val_mae: 0.1882
Epoch 37/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0160 - mae: 0.1003 - val_loss: 0.0621 - val_mae: 0.1937
Epoch 38/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0146 - mae: 0.0963 - val_loss: 0.0525 - val_mae: 0.1786
Epoch 39/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0130 - mae: 0.0910 - val_loss: 0.0530 - val_mae: 0.1789
Epoch 40/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0122 - mae: 0.0886 - val_loss: 0.0537 - val_mae: 0.1815
Epoch 41/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0117 - mae: 0.0872 - val_loss: 0.0531 - val_mae: 0.1776
Epoch 42/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0111 - mae: 0.0843 - val_loss: 0.0555 - val_mae: 0.1802
Epoch 43/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0103 - mae: 0.0814 - val_loss: 0.0490 - val_mae: 0.1727
Epoch 44/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0105 - mae: 0.0806 - val_loss: 0.0465 - val_mae: 0.1687
Epoch 45/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0098 - mae: 0.0791 - val_loss: 0.0435 - val_mae: 0.1615
Epoch 46/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0088 - mae: 0.0751 - val_loss: 0.0445 - val_mae: 0.1633
Epoch 47/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0085 - mae: 0.0732 - val_loss: 0.0405 - val_mae: 0.1552
Epoch 48/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0079 - mae: 0.0715 - val_loss: 0.0406 - val_mae: 0.1555
Epoch 49/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0083 - mae: 0.0724 - val_loss: 0.0429 - val_mae: 0.1606
Epoch 50/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0082 - mae: 0.0730 - val_loss: 0.0400 - val_mae: 0.1556
Epoch 51/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0065 - mae: 0.0641 - val_loss: 0.0414 - val_mae: 0.1593
Epoch 52/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0079 - mae: 0.0708 - val_loss: 0.0394 - val_mae: 0.1531
Epoch 53/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0083 - mae: 0.0725 - val_loss: 0.0403 - val_mae: 0.1547
Epoch 54/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0071 - mae: 0.0671 - val_loss: 0.0378 - val_mae: 0.1495
Epoch 55/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0066 - mae: 0.0644 - val_loss: 0.0378 - val_mae: 0.1473
Epoch 56/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0057 - mae: 0.0596 - val_loss: 0.0378 - val_mae: 0.1499
Epoch 57/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0060 - mae: 0.0621 - val_loss: 0.0364 - val_mae: 0.1461
Epoch 58/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0055 - mae: 0.0594 - val_loss: 0.0364 - val_mae: 0.1450
Epoch 59/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0055 - mae: 0.0586 - val_loss: 0.0361 - val_mae: 0.1444
Epoch 60/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0054 - mae: 0.0582 - val_loss: 0.0342 - val_mae: 0.1402
Epoch 61/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0054 - mae: 0.0577 - val_loss: 0.0334 - val_mae: 0.1392
Epoch 62/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0052 - mae: 0.0576 - val_loss: 0.0311 - val_mae: 0.1337
Epoch 63/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0059 - mae: 0.0612 - val_loss: 0.0365 - val_mae: 0.1474
Epoch 64/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0053 - mae: 0.0572 - val_loss: 0.0318 - val_mae: 0.1335
Epoch 65/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0053 - mae: 0.0579 - val_loss: 0.0319 - val_mae: 0.1365
Epoch 66/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0052 - mae: 0.0576 - val_loss: 0.0335 - val_mae: 0.1368
Epoch 67/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0060 - mae: 0.0610 - val_loss: 0.0305 - val_mae: 0.1338
Epoch 68/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0048 - mae: 0.0553 - val_loss: 0.0305 - val_mae: 0.1361
Epoch 69/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0056 - mae: 0.0590 - val_loss: 0.0340 - val_mae: 0.1451
Epoch 70/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0052 - mae: 0.0575 - val_loss: 0.0275 - val_mae: 0.1289
Epoch 71/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0050 - mae: 0.0554 - val_loss: 0.0278 - val_mae: 0.1267
Epoch 72/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0054 - mae: 0.0583 - val_loss: 0.0274 - val_mae: 0.1261
Epoch 73/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0044 - mae: 0.0530 - val_loss: 0.0292 - val_mae: 0.1338
Epoch 74/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0049 - mae: 0.0565 - val_loss: 0.0279 - val_mae: 0.1281
Epoch 75/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0051 - mae: 0.0572 - val_loss: 0.0278 - val_mae: 0.1278
Epoch 76/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0043 - mae: 0.0523 - val_loss: 0.0299 - val_mae: 0.1288
Epoch 77/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0051 - mae: 0.0565 - val_loss: 0.0267 - val_mae: 0.1261
Epoch 78/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0047 - mae: 0.0542 - val_loss: 0.0274 - val_mae: 0.1247
Epoch 79/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0043 - mae: 0.0510 - val_loss: 0.0287 - val_mae: 0.1324
Epoch 80/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0048 - mae: 0.0546 - val_loss: 0.0297 - val_mae: 0.1331
Epoch 81/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0065 - mae: 0.0646 - val_loss: 0.0329 - val_mae: 0.1391
Epoch 82/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0049 - mae: 0.0558 - val_loss: 0.0271 - val_mae: 0.1243
Epoch 83/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0059 - mae: 0.0607 - val_loss: 0.0272 - val_mae: 0.1281
Epoch 84/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0060 - mae: 0.0607 - val_loss: 0.0296 - val_mae: 0.1308
Epoch 85/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0050 - mae: 0.0554 - val_loss: 0.0254 - val_mae: 0.1242
Epoch 86/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0038 - mae: 0.0493 - val_loss: 0.0277 - val_mae: 0.1263
Epoch 87/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0045 - mae: 0.0534 - val_loss: 0.0230 - val_mae: 0.1163
Epoch 88/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0041 - mae: 0.0509 - val_loss: 0.0245 - val_mae: 0.1204
Epoch 89/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0038 - mae: 0.0489 - val_loss: 0.0247 - val_mae: 0.1185
Epoch 90/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0040 - mae: 0.0498 - val_loss: 0.0235 - val_mae: 0.1213
Epoch 91/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0030 - mae: 0.0431 - val_loss: 0.0242 - val_mae: 0.1170
Epoch 92/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0038 - mae: 0.0489 - val_loss: 0.0244 - val_mae: 0.1204
Epoch 93/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0044 - mae: 0.0525 - val_loss: 0.0254 - val_mae: 0.1228
Epoch 94/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0038 - mae: 0.0490 - val_loss: 0.0236 - val_mae: 0.1172
Epoch 95/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0027 - mae: 0.0416 - val_loss: 0.0222 - val_mae: 0.1131
Epoch 96/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0037 - mae: 0.0483 - val_loss: 0.0244 - val_mae: 0.1180
Epoch 97/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0028 - mae: 0.0415 - val_loss: 0.0260 - val_mae: 0.1223
Epoch 98/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0044 - mae: 0.0528 - val_loss: 0.0246 - val_mae: 0.1197
Epoch 99/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0039 - mae: 0.0478 - val_loss: 0.0251 - val_mae: 0.1232
Epoch 100/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0036 - mae: 0.0477 - val_loss: 0.0214 - val_mae: 0.1113
Epoch 101/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0025 - mae: 0.0390 - val_loss: 0.0230 - val_mae: 0.1145
Epoch 102/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0028 - mae: 0.0412 - val_loss: 0.0220 - val_mae: 0.1113
Epoch 103/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0026 - mae: 0.0397 - val_loss: 0.0208 - val_mae: 0.1081
Epoch 104/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0034 - mae: 0.0463 - val_loss: 0.0251 - val_mae: 0.1206
Epoch 105/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0054 - mae: 0.0585 - val_loss: 0.0301 - val_mae: 0.1321
Epoch 106/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0056 - mae: 0.0599 - val_loss: 0.0210 - val_mae: 0.1102
Epoch 107/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0052 - mae: 0.0563 - val_loss: 0.0231 - val_mae: 0.1160
Epoch 108/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0049 - mae: 0.0546 - val_loss: 0.0196 - val_mae: 0.1085
Epoch 109/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0041 - mae: 0.0507 - val_loss: 0.0188 - val_mae: 0.1024
Epoch 110/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0032 - mae: 0.0448 - val_loss: 0.0192 - val_mae: 0.1044
Epoch 111/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0036 - mae: 0.0467 - val_loss: 0.0220 - val_mae: 0.1152
Epoch 112/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0039 - mae: 0.0490 - val_loss: 0.0176 - val_mae: 0.1000
Epoch 113/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0026 - mae: 0.0399 - val_loss: 0.0187 - val_mae: 0.1053
Epoch 114/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0029 - mae: 0.0430 - val_loss: 0.0198 - val_mae: 0.1125
Epoch 115/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0048 - mae: 0.0539 - val_loss: 0.0166 - val_mae: 0.0998
Epoch 116/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0037 - mae: 0.0480 - val_loss: 0.0178 - val_mae: 0.1007
Epoch 117/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0032 - mae: 0.0441 - val_loss: 0.0182 - val_mae: 0.1011
Epoch 118/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0038 - mae: 0.0492 - val_loss: 0.0170 - val_mae: 0.1030
Epoch 119/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0052 - mae: 0.0563 - val_loss: 0.0199 - val_mae: 0.1105
Epoch 120/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0042 - mae: 0.0511 - val_loss: 0.0184 - val_mae: 0.1037
Epoch 121/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0042 - mae: 0.0515 - val_loss: 0.0179 - val_mae: 0.1012
Epoch 122/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0042 - mae: 0.0512 - val_loss: 0.0150 - val_mae: 0.0920
Epoch 123/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0024 - mae: 0.0392 - val_loss: 0.0149 - val_mae: 0.0932
Epoch 124/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0024 - mae: 0.0393 - val_loss: 0.0166 - val_mae: 0.0968
Epoch 125/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0027 - mae: 0.0409 - val_loss: 0.0163 - val_mae: 0.0966
Epoch 126/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0022 - mae: 0.0372 - val_loss: 0.0167 - val_mae: 0.0991
Epoch 127/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0022 - mae: 0.0370 - val_loss: 0.0142 - val_mae: 0.0921
Epoch 128/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0022 - mae: 0.0360 - val_loss: 0.0170 - val_mae: 0.0965
Epoch 129/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0035 - mae: 0.0466 - val_loss: 0.0158 - val_mae: 0.0951
Epoch 130/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0056 - mae: 0.0593 - val_loss: 0.0188 - val_mae: 0.1030
Epoch 131/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0039 - mae: 0.0501 - val_loss: 0.0139 - val_mae: 0.0903
Epoch 132/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0021 - mae: 0.0359 - val_loss: 0.0151 - val_mae: 0.0916
Epoch 133/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0014 - mae: 0.0302 - val_loss: 0.0145 - val_mae: 0.0893
Epoch 134/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0017 - mae: 0.0328 - val_loss: 0.0137 - val_mae: 0.0876
Epoch 135/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0016 - mae: 0.0309 - val_loss: 0.0145 - val_mae: 0.0898
Epoch 136/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0012 - mae: 0.0270 - val_loss: 0.0137 - val_mae: 0.0879
Epoch 137/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0025 - mae: 0.0397 - val_loss: 0.0153 - val_mae: 0.0909
Epoch 138/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0026 - mae: 0.0402 - val_loss: 0.0141 - val_mae: 0.0919
Epoch 139/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0022 - mae: 0.0364 - val_loss: 0.0162 - val_mae: 0.0938
Epoch 140/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0036 - mae: 0.0470 - val_loss: 0.0133 - val_mae: 0.0905
Epoch 141/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0024 - mae: 0.0384 - val_loss: 0.0130 - val_mae: 0.0866
Epoch 142/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0025 - mae: 0.0396 - val_loss: 0.0126 - val_mae: 0.0861
Epoch 143/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0035 - mae: 0.0469 - val_loss: 0.0155 - val_mae: 0.0945
Epoch 144/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0062 - mae: 0.0609 - val_loss: 0.0136 - val_mae: 0.0881
Epoch 145/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0032 - mae: 0.0442 - val_loss: 0.0149 - val_mae: 0.0902
Epoch 146/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0028 - mae: 0.0410 - val_loss: 0.0136 - val_mae: 0.0869
Epoch 147/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0029 - mae: 0.0425 - val_loss: 0.0136 - val_mae: 0.0888
Epoch 148/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0024 - mae: 0.0391 - val_loss: 0.0112 - val_mae: 0.0806
Epoch 149/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0019 - mae: 0.0340 - val_loss: 0.0121 - val_mae: 0.0833
Epoch 150/150
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0015 - mae: 0.0306 - val_loss: 0.0117 - val_mae: 0.0833

In [35]:
loss, mae = model.evaluate(X_test, y_test)

print("Test MAE:", mae)

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0119 - mae: 0.0817
Test MAE: 0.08166773617267609

In [36]:
model.save("sgpa5_prediction_model.h5")

print("Model saved as sgpa5_prediction_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Model saved as sgpa5_prediction_model.h5

In [37]:
loaded_model = load_model("sgpa5_prediction_model.h5", compile=False)

print("Model loaded successfully")

Model loaded successfully

In [39]:
predictions = loaded_model.predict(X_test)
print(predictions[:5])

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[[7.301551 ]
 [6.838526 ]
 [6.076255 ]
 [6.4996977]
 [8.643383 ]]

In [40]:
predictions = loaded_model.predict(X_test)
predictions = predictions.flatten()

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

In [41]:
X_test_df = pd.DataFrame(X_test, columns=X.columns)

In [42]:
X_test_df["predicted_sgpa5"] = predictions

X_test_df.head(20)

,sgpa1,sgpa2,sgpa3,sgpa4,cgpa,active_backlogs,total_backlogs,10th_mark,12th_mark,studytime,...,dsa,networks,os,attendance,career_preference,avg_sgpa_4,sgpa_trend,recent_trend,academic_score,predicted_sgpa5
0,0.014038,0.387779,-1.460095,-0.000690,-0.532389,2.372297,1.386128,0.506361,-1.738644,-0.497263,...,0.407236,0.843463,-1.104959,-1.596804,0.011481,-0.528720,-0.010364,1.039696,0.238661,7.301551
1,-0.552849,1.890242,-0.654508,-0.724813,-0.023274,2.372297,2.683848,0.335292,1.383465,-0.267182,...,0.562706,-0.741525,-0.183627,-0.980082,0.011481,-0.019570,-0.121454,-0.056425,-0.421333,6.838526
2,1.707523,0.394967,-0.015844,-1.025934,0.529480,1.445845,2.034988,0.543349,-0.011687,0.883224,...,1.236412,-0.230239,-1.053774,0.546042,0.011481,0.536858,-1.924139,-0.728575,-0.522871,6.076255
3,-1.464174,-0.359859,-0.444039,-0.739152,-1.521528,3.298750,2.034988,1.483460,1.034938,-0.267182,...,-1.510235,0.587820,1.351928,1.431054,0.011481,-1.521563,0.509738,-0.216707,-0.142105,6.499698
4,-0.732244,0.589066,-0.581932,0.859654,0.078549,-0.407060,-0.560453,-0.851406,-0.332519,-0.727344,...,-1.147470,-1.712970,1.710224,1.209801,0.011481,0.071349,1.120733,1.034526,0.162508,8.643383
5,-0.739420,1.279192,1.138105,-0.696135,0.485842,-0.407060,-0.560453,0.295735,0.994181,-1.417588,...,1.547353,0.843463,-1.156145,-0.832000,0.011481,0.489580,0.030032,-1.312828,0.543273,6.415446
6,-0.538498,0.962884,0.405093,0.350617,0.587665,0.519392,0.088407,-1.476606,-1.380712,-0.037101,...,0.251765,1.405878,-0.644293,-0.483569,1.236115,0.595046,0.625878,-0.035744,0.289430,7.956289
7,0.896659,-0.712111,-0.654508,0.902671,0.224011,-0.407060,-0.560453,1.668914,-0.662235,0.192981,...,-1.354764,-0.946040,0.737706,0.302141,0.011481,0.224094,0.004784,1.117252,-1.538246,8.132633
8,-0.495443,1.178549,0.891349,1.081910,1.344065,-0.407060,-0.560453,-0.267304,-0.835714,-0.497263,...,-0.940176,-0.281367,1.761409,0.372698,-1.213153,1.340587,1.110633,0.145220,1.076346,8.870778
9,-0.409334,1.796788,-0.277116,-0.660287,0.224011,-0.407060,-0.560453,1.585691,0.616393,0.883224,...,0.199942,0.894592,1.147187,0.444126,-1.213153,0.227731,-0.176999,-0.278751,0.898655,7.153145
10,0.997120,-2.200197,0.339775,-1.348563,-1.128781,-0.407060,0.088407,-0.947472,-0.803318,-0.037101,...,0.718177,1.457007,0.072299,0.404928,-1.213153,-1.121517,-1.651464,-1.214591,0.365583,4.729115
11,0.530694,0.553121,1.275998,0.995875,1.693172,-0.407060,-0.560453,-0.600710,0.200982,-0.267182,...,0.562706,0.383305,0.481780,-0.058485,-1.213153,1.693356,0.327955,-0.190855,0.873271,8.385459
12,0.028389,-0.273593,-1.133506,1.361522,0.005818,-0.407060,-0.560453,-0.766128,0.690069,-0.037101,...,-1.147470,-0.946040,0.277040,1.479835,-1.213153,-0.001387,0.938949,1.789402,-0.294411,9.179527
13,-0.107951,0.200869,0.680880,1.261148,1.024049,-0.407060,-0.560453,-0.179972,0.173811,0.883224,...,1.443706,-0.179110,0.481780,-0.762313,-1.213153,1.027824,0.964197,0.424421,0.314814,8.629418
14,0.380003,0.294324,-0.356949,-2.223246,-0.968774,-0.407060,-0.560453,-0.249838,1.201625,0.423062,...,-0.214647,-1.661841,-0.030071,0.172350,1.236115,-0.965135,-1.833248,-1.349021,-0.497486,4.779948
15,0.710089,0.840674,0.847803,0.071005,1.242241,-0.407060,-0.560453,-0.794383,0.204640,-1.417588,...,0.251765,-1.508455,1.761409,1.474608,-1.213153,1.246031,-0.449674,-0.552782,-0.116721,7.676628
16,0.875132,0.315890,0.753455,0.479669,1.227695,0.519392,0.088407,-0.662870,1.307176,0.883224,...,-0.162823,0.281048,-1.258515,0.173222,1.236115,1.224210,-0.277990,-0.190855,-0.573640,7.736662
17,1.119109,1.113849,-2.505181,1.218131,0.500388,1.445845,0.737267,-0.756368,-0.045129,-1.417588,...,-0.421941,1.047978,-1.104959,-0.129042,0.011481,0.493216,0.070428,2.663196,-0.725946,9.729204
18,0.143202,-0.381425,-0.001329,1.046062,0.413111,-0.407060,-0.560453,1.179851,0.861981,0.423062,...,1.651000,-1.355069,0.993632,-0.097683,1.236115,0.409570,0.635977,0.755325,-0.218258,8.297737
19,-1.894721,-2.624338,0.426866,1.555099,-1.288789,-0.407060,-0.560453,0.373307,-0.156950,-0.957425,...,0.044471,-0.537011,0.481780,-0.291933,-1.213153,-1.285172,2.428563,0.817370,-0.345180,7.989511

In [ ]:
# X_test_df.to_csv("sgpa5_predicted_dataset.csv", index=False)

# print("Dataset saved")